### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 13LuckyBack** [finlaysawyer/discord-uptime#30]
I am getting this error how can i fix this?

C:\Users\Administrator\Desktop\Lucky Ticket>python bot.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Lucky Ticket\bot.py", line 5, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'

**Comment by finlaysawyer** [comment]
You need to install `discord.py`, either using `pip install -r requirements.txt` in the bot's directory, or by doing `pip install discord.py`

**Comment by 13LuckyBack** [comment]
I still get the same problem.

**Comment by 13LuckyBack** [comment]
![image](https://user-images.githubusercontent.com/50382721/114613892-2d173f80-9ca4-11eb-8a7a-2920cce72870.png)

**Comment by finlaysawyer** [comment]
Do you perhaps have a folder named discord? 

Or multiple Python installations? `python -m pip install discord.py` should target the same installation that you're trying to run with

**Comment by 13LuckyBack** [comment]
Well now i did the command `python -m pip install discord.py` and now i am getting this error.

![image](https://user-images.githubusercontent.com/50382721/114614467-d3fbdb80-9ca4-11eb-896f-1539c0599695.png)

**Comment by finlaysawyer** [comment]
Ah, rename `example.config.json` to `config.json` and then fill in the config 😄

**Comment by 13LuckyBack** [comment]
Found the problem :(

**Comment by 13LuckyBack** [comment]
But he is not sending to the channel.

**Comment by 13LuckyBack** [comment]
![image](https://user-images.githubusercontent.com/50382721/114614734-2fc66480-9ca5-11eb-86f1-304066f68301.png)

**Comment by finlaysawyer** [comment]
Do `python -m pip install -r requirements.txt` to grab the other requirements

**Comment by 13LuckyBack** [comment]
Fixed.
Tank you so mutch!

**Comment by finlaysawyer** [comment]
No problem 😃

**Comment by 13LuckyBack** [comment]
Also one question where can i edit the Embad when i do the status command?

**Comment by finlaysawyer** [comment]
If you're talking about the servers that are tracked, you edit servers.json

If you want to edit the embed layout itself, you'll need to change the code
