### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by chunkoforanges** [finlaysawyer/discord-uptime#6]
I did this on glitch.com and when i put the token it said "bash: start.sh: No such file or directory". Is there any way to fix this?

**Comment by BlackKnight683** [comment]
run python bot.py in terminal

**Comment by finlaysawyer** [comment]
I haven't used Glitch before, but if it's asking for a `start.sh` script you'll need to create one yourself. As suggested above, it should just need to run `python bot.py`
