### ISSUE TITLE
Monitored services are showing as online even though they are unreachable

### ISSUE THREAD

**Issue by FatGrizzly** [finlaysawyer/discord-uptime#8]
![image](https://user-images.githubusercontent.com/66728880/107006796-b0557a00-67b7-11eb-85fb-23ab567b6b68.png)

**Comment by finlaysawyer** [comment]
Interesting, I'm not able to reproduce this. I'll probably need some form of debug from the requests being made in `monitor.py` to figure out why they aren't returning bad responses.

I know the method for checking via `http` is returning up for anything under `400`, so maybe I'll need to take a better look at that. I catch both `None` and `False` which are returned for bad pings, so not sure what is going on there.

![](https://i.gyazo.com/cf71c9ff373dae780cba74116ceb2dd1.png)

**Comment by FatGrizzly** [comment]
> I'll probably need some form of debug from the requests being made in monitor.py

Hmm, how do I give the logs?
Is it stored somewhere?

**Comment by finlaysawyer** [comment]
> Hmm, how do I give the logs?
> Is it stored somewhere?

There are no logs for this currently, so you'd need to add debug. Still looking like some kind of network or firewall issue to me.

**Comment by FatGrizzly** [comment]
Hmm, Yeah, it was indeed an firewall issue, fixed it up
