### ISSUE TITLE
remove the default help command

### ISSUE THREAD

**Issue by BlackKnight683** [finlaysawyer/discord-uptime#9]
I want to remove the default help command... any help?

i have tried doing both
```py
help_command=None
And
bot.remove_command("help")
```

![IMG_20210206_171000](https://user-images.githubusercontent.com/75422863/107117166-54b1ec00-689e-11eb-96c3-c04d282a43c9.jpg)
Kindly see the above and lemme know if im doing something wrong

**Comment by finlaysawyer** [comment]
The `DiscordUptime` class below overrides the original bot object. Add it there, i.e:

```py
class DiscordUptime(commands.Bot):
    def __init__(self):
        super().__init__(
            command_prefix=get_config("prefix"),
            description="Bot to monitor uptime of services",
            reconnect=True,
            intents=Intents.default(),
            help_command=None
        )
        self.bot = bot
```
